#!/bin/bash

usage(){
    U1="usage: $0 [-setcookie <cookie>] [-nocookie] "
    U2="[-nettick <tick>] [-nospawn] nodename"
    echo $U1 $U2
    exit
}

while [ -n "$1" ] 
  do
  ARGS="$ARGS $LAST"
  LAST=$1
  shift
done
echo args $ARGS
echo last $LAST
if [ -z "$LAST" ]; then usage; fi

Erl $ARGS \
-pa $JUNGERL/lib/prf/examples/dtop \
-pa $JUNGERL/lib/prf/ebin \
-s dtop start $LAST
