
include vsn.mk
include config/include.mk

APPLICATION=erlmerge
ERLMERGE=$(INSTALLPREFIX)/bin/$(APPLICATION)
ERL_LIB_DIR=$(INSTALLPREFIX)/lib
VERSION = $(ERLMERGE_VSN)
TARGETDIR=$(ERL_LIB_DIR)/$(APPLICATION)-$(VERSION)



all: script
	(cd src; $(MAKE) $@)

script: bin/erlmerge
	@(cp config/erlmerge.sh $<; \
	  echo 'EM_MAKE_USED='`which $(MAKE)` >> $<; \
	  echo 'export EM_MAKE_USED' >> $<; \
	  echo 'ERL_LIB_DIR='$(ERL_LIB_DIR) >> $<; \
	  echo 'export ERL_LIB_DIR' >> $<; \
	  echo '${ERL} -noshell -pa' $(TARGETDIR)/ebin '-s erlmerge run' >> $<; \
	  echo 'if [ "$${EM_SUICIDE}" = "y" ]; then rm -f `which erlmerge`; fi' >> $<)
#	  echo "ERL="$(ERL) >> erlmerge; \

bin/erlmerge: config/erlmerge.sh

clean:
	(cd src; $(MAKE) $@)

install:
	-rm $(INSTALLPREFIX)/support 
	-rm -rf $(INSTALLPREFIX)/erlmerge_DB
	install -d $(TARGETDIR)/priv
	install -d $(TARGETDIR)/ebin
	install -d $(TARGETDIR)/src
	install -d $(TARGETDIR)/include
	install -d $(INSTALLPREFIX)/erlmerge_DB
	install -d $(INSTALLPREFIX)/erlmerge_DB/distfiles
	ln -s $(INSTALLPREFIX)/erlmerge_DB $(INSTALLPREFIX)/support 
	install  config/include.mk $(INSTALLPREFIX)/erlmerge_DB
	install  src/*.erl $(TARGETDIR)/src
	install  ebin/*.beam $(TARGETDIR)/ebin
	install -d `dirname $(ERLMERGE)`
	install  ./bin/erlmerge $(ERLMERGE)
	chmod 755 $(ERLMERGE)
	-ln -s $(ERLMERGE) ${ERL}merge
	$(ERLMERGE) setup
