#!/bin/sh
#
# Note: require new getopt for -pa -pz handling etc
# Fixme: handle + arguments better (at all)
#
JERLHOME=/usr/local/jungerl/jungerl
EDEP="-pa $JERLHOME/lib/edep/ebin"
SYNTAX_TOOLS="-pa $JERLHOME/lib/syntax_tools/ebin"

opts=""
args=`getopt -n edep -a -o "PESWvI:o:D:b:" -l "MM,pa:,pz:" -- "$@"`
eval set -- "$args"

while [ $# -gt 0 ]
do
  case $1 in
      -W)   opts="$opts $1"; shift ;;
      -v)   opts="$opts $1"; shift ;; 
      -I)   opts="$opts $1 $2"; shift 2;;
      -o)   opts="$opts $1 $2"; shift 2;;
      -D)   opts="$opts $1$2"; shift 2;;
      -b)   opts="$opts $1 $2"; shift 2;;
      --pa) opts="$opts -pa $2"; shift 2;;
      --pz) opts="$opts -pz $2"; shift 2;;
      --MM) opts="$opts -MM"; shift 1;;
      +*)   opts="$opts $1"; shift ;; 
      --)   shift; break;;
      *)    break;;
  esac
done

erl -noinput $EDEP $SYNTAX_TOOLS  $opts -s edep start $*
