/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "stack.h"

void *
stackproc_null_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{
	static char * result;

	/*
	 * insert server code here
	 */

	return((void *) &result);
}

int *
stackproc_pop_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{
	static int  result;

	/*
	 * insert server code here
	 */

	return (&result);
}

bool_t *
stackproc_push_1(argp, rqstp)
	int *argp;
	struct svc_req *rqstp;
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return (&result);
}
