%%% This file was automatically generated by snmp_mib_to_hrl v3.0
%%% Date: 02-Nov-2003::23:10:26
-ifndef('TEST-MIB').
-define('TEST-MIB', true).

-define(test, [1,3,6,1,3,7]).
-define(testStr, [1,3,6,1,3,7,1]).
-define(testStr_instance, [1,3,6,1,3,7,1,0]).
-define(testInt, [1,3,6,1,3,7,2]).
-define(testInt_instance, [1,3,6,1,3,7,2,0]).

%% Range values
-define(low_testStr, 0).
-define(high_testStr, 255).


%% Default values
-define(default_testStr, []).
-define(default_testInt, 0).

-endif.
