%%%----------------------------------------------------------------------
%%% File    : spread_drv.hrl
%%% Summary : Spread toolkit version 3.17.0 driver
%%%
%%%
%%% NOTICE: This file was generated by the tools of the Erlang Driver
%%%         toolkit.  Do not edit this file by hand unless you know
%%%         what you're doing!
%%%
%%% Copyright (c) 2002, Scott Lystig Fritchie.  All rights reserved.
%%% See the file "LICENSE" at the top of the source distribution for
%%% full license terms.
%%%
%%%----------------------------------------------------------------------

-define(DRV_NAME, "spread_drv").

-define(MAX_UINT32, 16#FFFFFFFF).

-define(LEN_NUL_TERM, ?MAX_UINT32).

%%%
%%% Driver<->emulator communication codes (xref with top of spread_drv.h)
%%%

-define(_DEBUG,                         0).
-define(_SP_CONNECT,                    1).
-define(_SP_DISCONNECT,                 2).
-define(_SP_JOIN,                       3).
-define(_SP_LEAVE,                      4).
-define(_SP_MULTICAST,                  5).
-define(_SP_MULTIGROUP_MULTICAST,       6).
-define(_SP_POLL,                       7).
-define(_SP_RECEIVE,                    8).
-define(_SP_GET_GID_OFFSET_MEMB_MESS,   9).
-define(_SP_GET_NUM_VS_OFFSET_MEMB_MESS,  10).
-define(_SP_GET_VS_SET_OFFSET_MEMB_MESS,  11).
-define(_SET_ACTIVE,                    12).

%%%
%%% Constants
%%%

-ifndef(_MAX_MULTIGROUPS).
-define(_MAX_MULTIGROUPS,               64).    % Max number of groups in a multi-group multicast message
-endif.
-ifndef(_MAX_MSGLEN).
-define(_MAX_MSGLEN,                    (99*1024)).    % Max length of a multicast message
-endif.

%%%
%%% Verbatim stuff
%%%



-define(LOW_PRIORITY,    0).
-define(MEDIUM_PRIORITY, 1).
-define(HIGH_PRIORITY,   2).

-define(DEFAULT_SPREAD_PORT,     4803).

-define(UNRELIABLE_MESS,         16#00000001).
-define(RELIABLE_MESS,           16#00000002).
-define(FIFO_MESS,               16#00000004).
-define(CAUSAL_MESS,             16#00000008).
-define(AGREED_MESS,             16#00000010).
-define(SAFE_MESS,               16#00000020).
-define(REGULAR_MESS,            16#0000003f).

-define(SELF_DISCARD,            16#00000040).
-define(DROP_RECV,               16#01000000).

-define(REG_MEMB_MESS,           16#00001000).
-define(TRANSITION_MESS,         16#00002000).
-define(CAUSED_BY_JOIN,          16#00000100).
-define(CAUSED_BY_LEAVE,         16#00000200).
-define(CAUSED_BY_DISCONNECT,    16#00000400).
-define(CAUSED_BY_NETWORK,       16#00000800).
-define(MEMBERSHIP_MESS,         16#00003f00).

-define(ENDIAN_RESERVED,         16#80000080).
-define(RESERVED,                16#003fc000).
-define(REJECT_MESS,             16#00400000).

-define(ACCEPT_SESSION,           1).
-define(ILLEGAL_SPREAD,          -1).
-define(COULD_NOT_CONNECT,       -2).
-define(REJECT_QUOTA,            -3).
-define(REJECT_NO_NAME,          -4).
-define(REJECT_ILLEGAL_NAME,     -5).
-define(REJECT_NOT_UNIQUE,       -6).
-define(REJECT_VERSION,          -7).
-define(CONNECTION_CLOSED,       -8).
-define(REJECT_AUTH,             -9).

-define(ILLEGAL_SESSION,         -11).
-define(ILLEGAL_SERVICE,         -12).
-define(ILLEGAL_MESSAGE,         -13).
-define(ILLEGAL_GROUP,           -14).
-define(BUFFER_TOO_SHORT,        -15).
-define(GROUPS_TOO_SHORT,        -16).
-define(MESSAGE_TOO_LONG,        -17).

-define(MAX_GROUP_NAME,          32).
-define(MAX_PRIVATE_NAME,        10).%largest possible size of private_name field of SP_connect()
-define(MAX_PROC_NAME,           20).%largest possible size of process name of daemon




%%%
%%% End of autogenerated code
%%%  script = ../../edtk/hrl_template.gsl
%%%  filename = spread.xml
%%%  gslgen version = 2.000 Beta 1
%%%  date = 2003/05/20
%%%  time =  0:49:28
%%%
