%%%----------------------------------------------------------------------
%%% File    : gd1_drv.hrl
%%% Summary : An Erlang driver interface for libgd version 1
%%%
%%%
%%% NOTICE: This file was generated by the tools of the Erlang Driver
%%%         toolkit.  Do not edit this file by hand unless you know
%%%         what you're doing!
%%%
%%% Copyright (c) 2002, Scott Lystig Fritchie.  All rights reserved.
%%% See the file "LICENSE" at the top of the source distribution for
%%% full license terms.
%%%
%%%----------------------------------------------------------------------

-define(DRV_NAME, "gd1_drv").

-define(MAX_UINT32, 16#FFFFFFFF).

-define(LEN_NUL_TERM, ?MAX_UINT32).

%%%
%%% Driver<->emulator communication codes (xref with top of gd1_drv.h)
%%%

-define(_DEBUG,                         0).
-define(_GDIMAGECREATE,                 1).
-define(_GDIMAGECREATEFROMJPEG,         2).
-define(_GDIMAGECREATEFROMPNG,          3).
-define(_GDIMAGECREATEFROMGD,           4).
-define(_GDIMAGECREATEFROMGD2,          5).
-define(_GDIMAGECREATEFROMGD2PART,      6).
-define(_GDIMAGECREATEFROMXPM,          7).
-define(_GDIMAGECOLORALLOCATE,          8).
-define(_GDIMAGECOLORCLOSEST,           9).
-define(_GDIMAGECOLOREXACT,             10).
-define(_GDIMAGECOLORRESOLVE,           11).
-define(_GDIMAGECOLORSTOTAL,            12).
-define(_GDIMAGEGETINTERLACED,          13).
-define(_GDIMAGEGETTRANSPARENT,         14).
-define(_GDIMAGECOLORDEALLOCATE,        15).
-define(_GDIMAGECOLORTRANSPARENT,       16).
-define(_GDIMAGESETPIXEL,               17).
-define(_GDIMAGELINE,                   18).
-define(_GDIMAGEPOLYGON,                19).
-define(_GDIMAGEFILLEDPOLYGON,          20).
-define(_GDIMAGERECTANGLE,              21).
-define(_GDIMAGEFILLEDRECTANGLE,        22).
-define(_GDIMAGEARC,                    23).
-define(_GDIMAGEFILLTOBORDER,           24).
-define(_GDIMAGEFILL,                   25).
-define(_GDIMAGESETBRUSH,               26).
-define(_GDIMAGESETTILE,                27).
-define(_GDIMAGESETSTYLE,               28).
-define(_GDIMAGEGETPIXEL,               29).
-define(_GDIMAGERED,                    30).
-define(_GDIMAGEGREEN,                  31).
-define(_GDIMAGEBLUE,                   32).
-define(_GDIMAGEBOUNDSSAFE,             33).
-define(_GDIMAGESX,                     34).
-define(_GDIMAGESY,                     35).
-define(_GDIMAGEPNG,                    36).
-define(_GDIMAGEPNGPTR,                 37).
-define(_GDIMAGEPNGPTR_QQQ_DELETEME,    38).
-define(_GDIMAGEJPEG,                   39).
-define(_GDIMAGEJPEGPTR,                40).
-define(_GDIMAGEWBMP,                   41).
-define(_GDIMAGEWBMPPTR,                42).
-define(_GDIMAGEGD,                     43).
-define(_GDIMAGEGDPTR,                  44).
-define(_GDIMAGEGD2,                    45).
-define(_GDIMAGEGD2PTR,                 46).
-define(_FOPEN,                         47).
-define(_FCLOSE,                        48).
-define(_GDIMAGEPNGFILE,                49).
-define(_GDIMAGEJPEGFILE,               50).
-define(_GDIMAGEDESTROY,                51).
-define(_GETFONTPTR,                    52).
-define(_GDIMAGECHAR,                   53).
-define(_GDIMAGECHARUP,                 54).
-define(_GDIMAGESTRING,                 55).
-define(_GDIMAGESTRINGUP,               56).
-define(_GDIMAGECOPY,                   57).
-define(_GDIMAGECOPYRESIZED,            58).
-define(_GDIMAGECOPYMERGE,              59).
-define(_GDIMAGECOPYMERGEGRAY,          60).
-define(_GDIMAGEPALETTECOPY,            61).
-define(_GDIMAGECOMPARE,                62).
-define(_GDIMAGEINTERLACE,              63).

%%%
%%% Constants
%%%

-ifndef(_MAX_POLYGON_VERTICES).
-define(_MAX_POLYGON_VERTICES,          512).    % Max vertices/polygon
-endif.
-ifndef(_MAX_STYLE_LENGTH).
-define(_MAX_STYLE_LENGTH,              512).    % Max ints for style length
-endif.
-ifndef(_FONT_TINY).
-define(_FONT_TINY,                     1).    % gdFontTiny
-endif.
-ifndef(_FONT_SMALL).
-define(_FONT_SMALL,                    2).    % gdFontSmall
-endif.
-ifndef(_FONT_MEDIUMBOLD).
-define(_FONT_MEDIUMBOLD,               3).    % gdFontMediumBold
-endif.
-ifndef(_FONT_LARGE).
-define(_FONT_LARGE,                    4).    % gdFontLarge
-endif.
-ifndef(_FONT_GIANT).
-define(_FONT_GIANT,                    5).    % gdFontGiant
-endif.

%%%
%%% Verbatim stuff
%%%



%%%
%%% Useful constants from gd.h
%%%

-define(GD2_VERS,                       1).
-define(GD2_ID,                         "gd2").
-define(GD2_FMT_RAW,                    1).
-define(GD2_FMT_COMPRESSED,             2).

-define(GD2_gdMaxColors,                256).

-define(GD2_gdStyled,                   -2).
-define(GD2_gdBrushed,                  -3).
-define(GD2_gdStyledBrushed,            -4).
-define(GD2_gdTiled,                    -5).

-define(GD_CMP_IMAGE,                   1).
-define(GD_CMP_NUM_COLORS,              2).
-define(GD_CMP_COLOR,                   4).
-define(GD_CMP_SIZE_X,                  8).
-define(GD_CMP_SIZE_Y,                  16).
-define(GD_CMP_TRANSPARENT,             32).
-define(GD_CMP_BACKGROUND,              64).
-define(GD_CMP_INTERLACE,               128).



%%%
%%% End of autogenerated code
%%%  script = ../../edtk/hrl_template.gsl
%%%  filename = gd1.xml
%%%  gslgen version = 2.000 Beta 1
%%%  date = 2003/05/12
%%%  time = 21:06:37
%%%
