%%%----------------------------------------------------------------------
%%% File    : unixdom_drv.hrl
%%% Summary : EDTK implementation of UNIX domain socket driver (incomplete!)
%%%
%%%
%%% NOTICE: This file was generated by the tools of the Erlang Driver
%%%         toolkit.  Do not edit this file by hand unless you know
%%%         what you're doing!
%%%
%%% Copyright (c) 2004, Scott Lystig Fritchie.  All rights reserved.
%%% See the file "LICENSE" at the top of the source distribution for
%%% full license terms.
%%%
%%%----------------------------------------------------------------------

-define(DRV_NAME, "unixdom_drv").

-define(MAX_UINT32, 16#FFFFFFFF).

-define(LEN_NUL_TERM, ?MAX_UINT32).

%%%
%%% Driver<->emulator communication codes (xref with top of unixdom_drv.h)
%%%

-define(S1_DEBUG,                       0).
-define(S1_NULL,                        1).
-define(S1_OPEN,                        2).
-define(S1_GETFD,                       3).
-define(S1_SENDFD,                      4).
-define(S1_RECEIVEFD,                   5).
-define(S1_CLOSE,                       6).
-define(S1_WRITE,                       7).
-define(S1_READ,                        8).

%%%
%%% Constants
%%%


%%%
%%% Verbatim stuff
%%%


%%%
%%% End of autogenerated code
%%%  script = ../../edtk/hrl_template.gsl
%%%  filename = unixdom.xml
%%%  gslgen version = 2.000 Beta 1
%%%  date = 2004/02/23
%%%  time =  2:24:54
%%%
