.TH epop_inc 3 1998-08-18 "Ericsson Telecom AB" "ERLANG MODULE DEFINITION"
.SH MODULE
Epop - A POP3 client/server package \- The Epop local mail delivery agent
.SH DESCRIPTION
.LP
According to the Epop configuration file <epop_configure.html>, start retreiving mails. 

.SH EXPORTS
.LP
.B
start()
.br
.RS
.LP
Start the local mail delivery agent. 
.RE
.SH More information
.LP
Latest information about Epop can be found at the Epop homepage <http://www.serc.rmit.edu.au/~tobbe/epop>\&.
.SH AUTHOR
.nf
T.Tornkvist - tobbe@cslab.ericsson.se
.fi
