
DICTMAPS=dictionary.map \
	 dictionary_acc.map \
	 dictionary_alcatel.map \
	 dictionary_alteon.map \
	 dictionary_altiga.map \
	 dictionary_aptis.map \
	 dictionary_ascend.map \
	 dictionary_bay.map \
	 dictionary_bintec.map \
	 dictionary_cabletron.map \
	 dictionary_cisco.map \
	 dictionary_cisco_bbsm.map \
	 dictionary_cisco_vpn3000.map \
	 dictionary_cisco_vpn5000.map \
	 dictionary_colubris.map \
	 dictionary_columbia_university.map \
	 dictionary_compat.map \
	 dictionary_erx.map \
	 dictionary_extreme.map \
	 dictionary_foundry.map \
	 dictionary_freeradius.map \
	 dictionary_itk.map \
	 dictionary_juniper.map \
	 dictionary_livingston.map \
	 dictionary_microsoft.map \
	 dictionary_netscreen.map \
	 dictionary_nokia.map \
	 dictionary_nomadix.map \
	 dictionary_quintum.map \
	 dictionary_redback.map \
	 dictionary_redcreek.map \
	 dictionary_shasta.map \
	 dictionary_shiva.map \
	 dictionary_springtide.map \
	 dictionary_telebit.map \
	 dictionary_tunnel.map \
	 dictionary_usr.map \
	 dictionary_versanet.map \
	 dictionary_wispr.map \
	 dictionary_xedia.map


all: $(DICTMAPS)

clean:  
	-rm *.map ../include/dictionary*.hrl

dictionary.map: dictionaries/dictionary
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_acc.map: dictionaries/dictionary.acc
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_alcatel.map: dictionaries/dictionary.alcatel
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_alteon.map: dictionaries/dictionary.alteon
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_altiga.map: dictionaries/dictionary.altiga
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_aptis.map: dictionaries/dictionary.aptis
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_ascend.map: dictionaries/dictionary.ascend
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_bay.map: dictionaries/dictionary.bay
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_bintec.map: dictionaries/dictionary.bintec
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_cabletron.map: dictionaries/dictionary.cabletron
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_cisco.map: dictionaries/dictionary.cisco
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_cisco_bbsm.map: dictionaries/dictionary.cisco.bbsm
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_cisco_vpn3000.map: dictionaries/dictionary.cisco.vpn3000
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_cisco_vpn5000.map: dictionaries/dictionary.cisco.vpn5000
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_colubris.map: dictionaries/dictionary.colubris
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_columbia_university.map: dictionaries/dictionary.columbia_university
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_compat.map: dictionaries/dictionary.compat
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_erx.map: dictionaries/dictionary.erx
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_extreme.map: dictionaries/dictionary.extreme
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_foundry.map: dictionaries/dictionary.foundry
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_freeradius.map: dictionaries/dictionary.freeradius
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_itk.map: dictionaries/dictionary.itk
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_juniper.map: dictionaries/dictionary.juniper
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_livingston.map: dictionaries/dictionary.livingston
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_microsoft.map: dictionaries/dictionary.microsoft
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_netscreen.map: dictionaries/dictionary.netscreen
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_nokia.map: dictionaries/dictionary.nokia
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_nomadix.map: dictionaries/dictionary.nomadix
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_quintum.map: dictionaries/dictionary.quintum
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_redback.map: dictionaries/dictionary.redback
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_redcreek.map: dictionaries/dictionary.redcreek
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_shasta.map: dictionaries/dictionary.shasta
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_shiva.map: dictionaries/dictionary.shiva
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_springtide.map: dictionaries/dictionary.springtide
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_telebit.map: dictionaries/dictionary.telebit
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_tunnel.map: dictionaries/dictionary.tunnel
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_usr.map: dictionaries/dictionary.usr
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_versanet.map: dictionaries/dictionary.versanet
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_wispr.map: dictionaries/dictionary.wispr
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

dictionary_xedia.map: dictionaries/dictionary.xedia
	@erl -noshell -pa ../ebin -s eradius_dict make $^ || exit 1;

