#!/bin/bash

if [ $# -ne 2 ]; then
    exit
fi
PKG="$1"
PK="$2"

CFLAGS=`pkg-config --cflags "$PKG"`
PTH=""
for f in $CFLAGS; do
    if [ "`echo "$f" | grep "include/$PK"`" != "" ]; then
        PTH=`echo "$f" | cut -c3-`
    fi
done
echo $PTH

